package com.example.thirdeye;

import static com.example.thirdeye.SplashScreen.translationsMap;

public class instructionmap {
    public static void makeinstruction() {
        // Create a HashMap to store translations for each language

        translationsMap.put("en", "•   The main screen has three channels accessible to assist you in your everyday activities: read, object, and translate, which are represented by the buttons below.\n•   One microphone button is located in the middle of the app's main screen, and you may use it to open any channel you like. For example, say 'read' and it will take you there.\n•   There is a setting button on the right side of the top navigation bar and clicking it will give you options to customize our app: Default Language, Speech Rate (how quickly you want the app to speak), and Partially Blind (enable it if you are not completely blind).");

        // Afrikaans
        translationsMap.put("af", "•   Die hoofskerm het drie kanale wat beskikbaar is om jou te help met jou alledaagse aktiwiteite: lees, voorwerp, en vertaal, wat deur die knoppies hieronder verteenwoordig word.\nEen mikrofoonknoppie is in die middel van die program se hoofskerm, en jy kan dit gebruik om enige kanaal wat jy verkies, oop te maak.\nVoorbeeld: sê 'lees' en dit sal jou daarheen neem.\n•   Daar is ook 'n instellingsknoppie aan die regterkant van die boonste navigasiestaaf, en deur daarop te klik, sal jy opsies kry om ons program aan te pas:\nDefault Language, Speech Rate (hoe vinnig wil jy hê dat die program praat), en Gedeeltelik blind (aktiveer dit as jy nie heeltemal blind is nie).");

        // Arabic
        translationsMap.put("ar", "•   الشاشة الرئيسية تحتوي على ثلاث قنوات قابلة للوصول لمساعدتك في أنشطتك اليومية: قراءة، وكائن، وترجمة، والتي تمثلها الأزرار أدناه.\nيوجد زر ميكروفون واحد في منتصف شاشة التطبيق الرئيسية، ويمكنك استخدامه لفتح أي قناة تفضلها.\nعلى سبيل المثال، قل 'قراءة' وسيأخذك إلى هناك.\n•   هناك أيضًا زر إعدادات على الجانب الأيمن من شريط التنقل العلوي، وبالنقر عليه، ستحصل على خيارات لتخصيص تطبيقنا:\nDefault Language, Speech Rate (كم سرعة ترغب في أن يتحدث التطبيق)، والعمى الجزئي (قم بتمكينه إذا لم تكن مكفوفًا تمامًا).");

        // Bengali
        translationsMap.put("bn", "•   মূল স্ক্রিনে আপনার প্রতিদিনের কার্যক্রমে আপনাকে সহায়তা করার জন্য তিনটি চ্যানেল অ্যাক্সেসযোগ্য: পড়া, বস্তু, এবং অনুবাদ, যা নীচের বাটনের মাধ্যমে প্রতিনিধিত করা হয়।\nএকটি মাইক্রোফোন বোতাম মূল অ্যাপ্লিকেশনের মধ্যে অবস্থিত এবং আপনি যে কোনও চ্যানেল খুলতে এটি ব্যবহার করতে পারেন।\nউদাহরণস্বরূপ, 'পড়ুন' বলুন এবং এটি আপনাকে তাতে নিয়ে যাবে।\n•   শীর্ষ নেভিগেশন বারের ডান দিকে একটি সেটিং বাটন রয়েছে এবং এটিতে ক্লিক করলে আপনি আমাদের অ্যাপ্লিকেশন কাস্টমাইজ করার বিকল্পগুলি পাবেন:\nDefault Language, Speech Rate (আপনি কত দ্রুত আপলিকেশনটি স্পীক করতে চান), এবং অংশত: অন্ধ (যদি আপনি সম্পূর্ণ অন্ধ না হন।)");

        // Bulgarian
        translationsMap.put("bg", "•   Главният екран има три достъпни канала, които да ви помогнат в ежедневните ви дейности: четене, обект и превод, които се представят с бутоните по-долу.\nЕдин бутон за микрофон е разположен в средата на главния екран на приложението и можете да го използвате, за да отворите който и да е канал, който предпочитате.\nНапример, кажете 'четене' и това ще ви отведе там.\n•   Има също бутон за настройки в дясната част на горния навигационен лент");


        // Chinese
        translationsMap.put("zh", "•   主屏幕有三个可访问的频道，可帮助您进行日常活动：阅读、对象和翻译，这些频道由下面的按钮表示。\n主屏幕中央有一个麦克风按钮，您可以使用它来打开您喜欢的任何频道。例如，说'阅读'，它会带您到那里。\n•   顶部导航栏右侧有一个设置按钮，单击它将给您自定义应用程序的选项：默认语言、语音速率（您希望应用程序说话的速度有多快）和部分盲人（如果您不是完全失明，则启用它）。\n");

        // Czech
        translationsMap.put("cs", "•   Hlavní obrazovka obsahuje tři kanály přístupné k asistenci při vašich každodenních aktivitách: čtení, objekt a překlad, které jsou reprezentovány tlačítky níže.\nV prostřední části hlavní obrazovky aplikace se nachází jedno tlačítko mikrofonu a můžete jej použít k otevření libovolného kanálu, který si přejete. Například řekněte 'čtení' a přenesu vás tam.\n•   V pravé části horní navigační lišty je tlačítko nastavení a kliknutím na něj získáte možnosti přizpůsobení naší aplikace: výchozí jazyk, rychlost řeči (jak rychle chcete, aby aplikace mluvila), a částečně slepí (povolte to, pokud nejste úplně slepí).\n");

        // Danish
        translationsMap.put("da", "•   Hovedskærmen har tre kanaler, der er tilgængelige for at hjælpe dig med dine daglige aktiviteter: læs, objekt og oversæt, som repræsenteres af knapperne nedenfor.\nDer er en mikrofonknap i midten af appens hovedskærm, og du kan bruge den til at åbne en hvilken som helst kanal, du ønsker. For eksempel, sig 'læs', og det vil tage dig derhen.\n•   Der er også en indstillingsknap på højre side af den øverste navigationslinje, og ved at klikke på den får du muligheder for at tilpasse vores app: Standardsprog, Talehastighed (hvor hurtigt du vil have appen til at tale), og Delvist blind (aktiver det, hvis du ikke er helt blind).\n");

        // Dutch
        translationsMap.put("nl", "•   Het hoofdscherm heeft drie kanalen die toegankelijk zijn om u te helpen bij uw dagelijkse activiteiten: lezen, object en vertalen, die worden vertegenwoordigd door de onderstaande knoppen.\nEen microfoonknop bevindt zich in het midden van het hoofdscherm van de app, en u kunt deze gebruiken om elk gewenst kanaal te openen. Bijvoorbeeld, zeg 'lezen' en het brengt u daarheen.\n•   Aan de rechterkant van de bovenste navigatiebalk bevindt zich een instellingenknop en door erop te klikken krijgt u opties om onze app aan te passen: Standaardtaal, Spreeksnelheid (hoe snel u wilt dat de app spreekt), en Gedeeltelijk blind (activeer het als u niet helemaal blind bent).\n");

// Finnish
        translationsMap.put("fi", "•   Pääruudussa on kolme kanavaa, jotka ovat käytettävissä auttamaan sinua päivittäisissä toiminnoissasi: lue, objekti ja käännä, jotka on edustettu alla olevilla painikkeilla.\nSovelluksen pääruudun keskellä on mikrofonipainike, ja voit käyttää sitä avataksesi haluamasi kanavan. Esimerkiksi sano 'lue' ja se vie sinut sinne.\n•   Ylävalikon oikealla puolella on asetus-painike, ja sitä napsauttamalla saat vaihtoehdot sovelluksemme mukauttamiseen: Oletuskieli, Puhetahti (kuinka nopeasti haluat sovelluksen puhuvan) ja Osittain sokea (ota se käyttöön, jos et ole täysin sokea).\n");

        // French
        translationsMap.put("fr", "•   L'écran principal comporte trois chaînes accessibles pour vous aider dans vos activités quotidiennes : lire, objet et traduire, qui sont représentées par les boutons ci-dessous.\nUn bouton de microphone est situé au milieu de l'écran principal de l'application, et vous pouvez l'utiliser pour ouvrir n'importe quelle chaîne que vous souhaitez. Par exemple, dites 'lire' et cela vous y emmènera.\n•   Il y a également un bouton de paramètres sur le côté droit de la barre de navigation supérieure et en cliquant dessus, vous aurez des options pour personnaliser notre application : Langue par défaut, Taux de parole (à quelle vitesse vous voulez que l'application parle), et Partiellement aveugle (activez-le si vous n'êtes pas complètement aveugle).\n");

        // Galician
        translationsMap.put("gl", "•   A pantalla principal ten tres canles accesibles para axudarche nas túas actividades diarias: ler, obxecto e traducir, que se representan cos botóns abaixo.\nUn botón de micrófono está situado no medio da pantalla principal da aplicación, e podes usalo para abrir calquera canle que che guste. Por exemplo, di 'ler' e levarache ata alí.\n•   Hai tamén un botón de configuración no lado dereito da barra de navegación superior e facendo clic nel, terás opcións para personalizar a nosa aplicación: Idioma predeterminado, Taxa de fala (a que velocidade queres que a aplicación fale) e Parcialmente cego (actívalo se non estás completamente cego).\n");

// German
        translationsMap.put("de", "•   Der Hauptbildschirm verfügt über drei zugängliche Kanäle, um Sie bei Ihren täglichen Aktivitäten zu unterstützen: lesen, Objekt und übersetzen, die durch die unten stehenden Schaltflächen repräsentiert werden.\nEine Mikrofon-Schaltfläche befindet sich in der Mitte des Hauptbildschirms der App, und Sie können sie verwenden, um jeden gewünschten Kanal zu öffnen. Zum Beispiel sagen Sie 'lesen' und es bringt Sie dorthin.\n•   Auf der rechten Seite der oberen Navigationsleiste befindet sich eine Einstellungsschaltfläche, und durch Klicken darauf erhalten Sie Optionen zur Anpassung unserer App: Standardsprache, Sprechgeschwindigkeit (wie schnell Sie möchten, dass die App spricht), und Teilweise blind (aktivieren Sie es, wenn Sie nicht vollständig blind sind).\n");

        // Greek
        translationsMap.put("el", "•   Η κύρια οθόνη διαθέτει τρεις κανάλια προσβασιμότητας για να σας βοηθήσει στις καθημερινές δραστηριότητές σας: ανάγνωση, αντικείμενο και μετάφραση, τα οποία εκπροσωπούνται από τα κουμπιά παρακάτω.\nΈνα κουμπί μικροφώνου βρίσκεται στη μέση της κύριας οθόνης της εφαρμογής και μπορείτε να το χρησιμοποιήσετε για να ανοίξετε οποιοδήποτε κανάλι θέλετε. Για παράδειγμα, πείτε 'ανάγνωση' και θα σας οδηγήσει εκεί.\n•   Υπάρχει επίσης ένα κουμπί ρυθμίσεων στη δεξιά πλευρά της επάνω γραμμής πλοήγησης και κάνοντας κλικ εκεί θα έχετε επιλογές για να προσαρμόσετε την εφαρμογή μας: Προεπιλεγμένη γλώσσα, Ταχύτητα ομιλίας (πόσο γρήγορα θέλετε να μιλάει η εφαρμογή), και Μερικώς τυφλός (ενεργοποιήστε το αν δεν είστε πλήρως τυφλός).\n");

        // Gujarati
        translationsMap.put("gu", "•   મુખ્ય સ્ક્રીન દરરોજની તમારી સાથે સહાય કરવા માટે ત્રણ ચેનલ્સ ઉપલબ્ધ છે: વાંચો, ઑબ્જેક્ટ, અને ટ્રાન્સલેટ, જે નીચેના બટનો દ્વારા પ્રતિનિધિત કરવામાં આવે છે.\nએપ્લિકેશનની મુખ્ય સ્ક્રીનમાં એક માઇક્રોફોન બટન હોય છે, અને તમે તેનો ઉપયોગ કરીને તમારી પસંદગી કોઈ પણ ચેનલ ખોલી શકો છો. ઉદાહરણ તરીકે, 'વાંચો' કહો અને તે તમને તેને લઈ જશે.\n•   પ્રમુખ નૅવિગેશન બારના ડાબા બાજુમાં એક સેટિંગ્સ બટન છે અને તેને ક્લિક કરીને તમારી એપ્લિકેશનને કસ્ટમાઇઝ કરવાની વિકલ્પો મળે: ડિફોલ્ટ ભાષા, બોલાવણી ગતિ (તમે કેવી ઝડપથી એપ્લિકેશન બોલે તે), અને અંશદારે અંધો (જો તમે પૂરેપૂરી અંધા નથી તો તેને સક્રિય કરો).\n");

// Hindi
        translationsMap.put("hi", "•   मुख्य स्क्रीन में तीन चैनल हैं जो आपकी दैनिक गतिविधियों में आपकी सहायता के लिए उपलब्ध हैं: पढ़ें, ऑब्जेक्ट, और ट्रांसलेट, जिन्हें नीचे के बटनों द्वारा प्रतिनिधित किया गया है।\nएक माइक्रोफोन बटन ऐप की मुख्य स्क्रीन के बीच में स्थित है, और आप इसका उपयोग करके किसी भी चैनल को खोल सकते हैं। उदाहरण के लिए, 'पढ़ें' कहें और यहाँ ले जाएगा।\n•   अप्प के शीर्ष नेविगेशन बार के दाईं ओर एक सेटिंग बटन है और उसे क्लिक करने पर आपको हमारे एप्लिकेशन को अनुकूलित करने के विकल्प मिलेंगे: डिफ़ॉल्ट भाषा, बोलने की गति (आप चाहें तो ऐप को कितनी तेज़ी से बोलना चाहते हैं), और आंशिक अंधा (अगर आप पूरी तरह से अंधे नहीं हैं तो इसे सक्रिय करें)।\n");

        // Hungarian
        translationsMap.put("hu", "•   A főképernyőn három csatorna található, amelyek segítenek mindennapi tevékenységeiben: olvasás, objektum és fordítás, amelyeket az alábbi gombok jelölnek.\nEgy mikrofon gomb található az alkalmazás főképernyőjének közepén, amelyet bármelyik kívánt csatorna megnyitására használhat. Például mondja el, hogy 'olvas', és elvisz oda.\n•   A felső navigációs sáv jobb oldalán egy beállítás gomb található, és ha rákattint, beállítási lehetőségek jelennek meg az alkalmazás testreszabásához: Alapértelmezett nyelv, Beszédsebesség (milyen gyorsan szeretné, hogy az alkalmazás beszéljen), és Részben vakság (engedélyezze, ha nem teljesen vak).\n");

        // Icelandic
        translationsMap.put("is", "•   A aðalskjárinn hefur þrjú rafrásir aðgengileg til að aðstoða þig í daglegum athöfnum þínum: lesa, hlutur og þýða, sem eru táknrænt með hnappum hér fyrir neðan.\nEinn hljóðnemihnappur er staðsettur í miðju aðalskjár forritsins, og þú getur notað hann til að opna hvaða rás sem þú vilt. Til dæmis segirðu 'lesa' og það mun taka þig þangað.\n•   Á hægri hlið efstu stýriðsliðarins er stillingarhnappur og með því að smella á hann færðu valkosti til að sérsníða forritið okkar: Sjálfgefin tungumál, Raðtala (hversu hratt þú vilt að forritið tali), og Að hluta til blindur (virkjaðu það ef þú ert ekki alveg blindur).\n");

        translationsMap.put("id", "•   Layar utama memiliki tiga saluran yang dapat diakses untuk membantu Anda dalam aktivitas sehari-hari: baca, objek, dan terjemahkan, yang direpresentasikan oleh tombol di bawah.\nTerdapat satu tombol mikrofon yang terletak di tengah layar utama aplikasi, dan Anda dapat menggunakannya untuk membuka saluran apa pun yang Anda inginkan. Misalnya, katakan 'baca' dan itu akan membawa Anda ke sana.\n•   Terdapat tombol pengaturan di sisi kanan bilah navigasi atas dan mengkliknya akan memberikan opsi untuk menyesuaikan aplikasi kami: Bahasa Default, Tingkat Bicara (seberapa cepat Anda ingin aplikasi berbicara), dan Sebagian Buta (aktifkan jika Anda tidak benar-benar buta).\n");

        // Italian
        translationsMap.put("it", "•   La schermata principale ha tre canali accessibili per assisterti nelle tue attività quotidiane: leggere, oggetti e tradurre, rappresentati dai pulsanti qui sotto.\nUn pulsante del microfono è posizionato al centro della schermata principale dell'app e puoi usarlo per aprire qualsiasi canale desideri. Ad esempio, di 'leggere' e ti porterà lì.\n•   C'è un pulsante delle impostazioni sul lato destro della barra di navigazione superiore e facendo clic su di esso ti darà opzioni per personalizzare la nostra app: Lingua predefinita, Velocità di lettura (quanto velocemente vuoi che l'app parli) e Parzialmente Cieco (abilitarlo se non sei completamente cieco).\n");

        // Japanese
        translationsMap.put("ja", "•   メイン画面には、日常の活動を支援するためにアクセス可能な3つのチャンネルがあります：読む、オブジェクト、および翻訳、これらは下のボタンで表されています。\nアプリのメイン画面の中央には1つのマイクボタンがあり、それを使用して任意のチャンネルを開くことができます。たとえば、「読む」と言うと、そこに移動します。\n•   上部ナビゲーションバーの右側に設定ボタンがあり、それをクリックするとアプリをカスタマイズするオプションが表示されます：デフォルトの言語、スピーチレート（アプリが話す速さ）、および部分的に盲目（完全に盲目でない場合は有効にします）。\n");

// Kannada
        translationsMap.put("kn", "•   ಪ್ರತಿದಿನದ ಕೆಲಸಗಳಲ್ಲಿ ನಿಮಗೆ ಸಹಾಯ ಮಾಡಲು ಮೂರು ಚಾನೆಲ್‌ಗಳಿವೆ: ಓದಿ, ವಸ್ತು, ಮತ್ತು ಭಾಷಾಂತರಿಸಿ, ಇವುಗಳನ್ನು ಕೆಳಗಿನ ಬಟನ್‌ಗಳಿಂದ ಪ್ರತಿನಿಧಿಸಲಾಗಿದೆ.\nಆಪ್‌ನ ಮುಖ್ಯ ಪಟದಲ್ಲಿ ಒಂದು ಮೈಕ್ರೊಫೋನ್ ಬಟನ್‌ನು ಇರುವುದು ಮತ್ತು ನೀವು ಅದನ್ನು ಬಳಸಿ ನೀವು ಯಾವುದಾದರೂ ಚಾನೆಲ್‌ನನ್ನು ತೆರೆಯಬಹುದು. ಉದಾಹರಣೆಗೆ, 'ಓದಿ' ಎಂದು ಹೇಳಿ ಅದು ನಿಮ್ಮನ್ನು ಅಲ್ಲಿಗೆ ಕರೆಸುತ್ತದೆ.\n•   ಮೇಲಿನ ನೇವಿಗೇಷನ್ ಬಾರ್‌ನ ಬಲ ಭಾಗದಲ್ಲಿ ಸೆಟ್ಟಿಂಗ್‌ಗಳ ಬಟನ್‌ಗಳಿವೆ ಮತ್ತು ಅದನ್ನು ಕ್ಲಿಕ್‌ಮಾಡುವುದರಿಂದ ನಮ್ಮ ಆ್ಯಪ್‌ನನ್ನು ಕಸ್ಟಮೈಸ್ ಮಾಡಲು ಆಯ್ಕೆಗಳು ಲಭ್ಯವಾಗುತ್ತವೆ: ಡೀಫಾಲ್ಟ್ ಭಾಷೆ, ಬಾಯಿಕದ ಗತಿ (ನೀವು ಆ್ಯಪ್‌ನ್‌ನನ್ನು ಹೇಗೆ ಬೆರಕೆ ಮಾಡಬಯಸುತ್ತೀರಿ ಎಂಬುದರಲ್ಲಿ ಎಷ್ಟು ಬೇಗ ನೀವು ಬಯಸುತ್ತೀರಿ), ಮತ್ತು ಭಾಗದಾರಿಕ ಕುರುಡು (ಪೂರ್ಣವಾಗಿ ಕುರುಡಲ್ಲದಿದ್ದರೆ ಅದನ್ನು ಸಕ್ರಿಯಗೊಳಿಸಿ).\n");

        // Korean
        translationsMap.put("ko", "•   주 화면에는 일상적인 활동을 지원하기 위해 접근 가능한 세 가지 채널이 있습니다: 읽기, 물건, 번역, 아래 버튼에 의해 나타납니다.\n앱의 주 화면 중앙에는 마이크 버튼이 하나 있으며 이를 사용하여 원하는 채널을 열 수 있습니다. 예를 들어 '읽기'라고 말하면 해당 채널로 이동합니다.\n•   상단 네비게이션 바 오른쪽에는 설정 버튼이 있으며 클릭하면 앱을 사용자 정의하는 옵션을 제공합니다: 기본 언어, 말하기 속도 (앱이 얼마나 빨리 말할지), 그리고 부분적으로 시각 장애인 (완전히 시각 장애가 아닌 경우 활성화).\n");

        // Latvian
        translationsMap.put("lv", "•   Galvenajā ekrānā ir trīs kanāli, kas ir pieejami, lai palīdzētu jums ikdienas darbos: lasīt, objekts un tulkot, kas ir atspoguļoti zemāk redzamajos pogās.\nViena mikrofona poga atrodas lietotnes galvenajā ekrānā, un to varat izmantot, lai atvērtu jebkuru vēlamo kanālu. Piemēram, sakiet 'lasīt', un jūs tiksiet tur.\n•   Virsējā navigācijas joslas labajā pusē ir iestatījumu poga, un to noklikšķinot, tiks sniegtas iespējas pielāgot mūsu lietotni: noklusējuma valoda, runas ātrums (cik ātri vēlaties, lai lietotne runā), un daļēji aklie (aktivizējiet to, ja jums nav pilnībā redzes trūkums).\n");

// Lithuanian
        translationsMap.put("lt", "•   Pagrindiniame ekrane yra trys kanalai, prieinami padėti jums kasdienėse veiklose: skaityti, objektas ir versti, kurie yra pavaizduoti žemiau esančiuose mygtukuose.\nVienas mikrofono mygtukas yra programos pagrindiniame ekrane, ir jūs galite jį naudoti, norėdami atidaryti bet kurį norimą kanalą. Pavyzdžiui, sakykite „skaityti“, ir jūs būsite ten.\n•   Viršutinėje naršymo juostoje dešinėje pusėje yra nustatymo mygtukas, ir paspaudus jį, bus suteiktos galimybės pritaikyti mūsų programą: numatytasis kalbas, kalbėjimo greitį (kaip greitai norite, kad programa kalbėtų), ir dalinai aklų (įjungti, jei esate ne visiškai aklas).\n");

        // Malay
        translationsMap.put("ms", "•   Skrin utama mempunyai tiga saluran yang boleh diakses untuk membantu anda dalam aktiviti harian anda: baca, objek, dan terjemah, yang diwakili oleh butang di bawah.\nTerdapat satu butang mikrofon yang terletak di tengah skrin utama aplikasi, dan anda boleh menggunakannya untuk membuka mana-mana saluran yang anda suka. Sebagai contoh, katakan 'baca' dan ia akan membawa anda ke sana.\n•   Terdapat butang tetapan di bahagian kanan bar navigasi atas dan mengkliknya akan memberikan pilihan untuk menyesuaikan aplikasi kami: Bahasa Lalai, Kadar Pertuturan (berapa cepat anda mahu aplikasi bercakap), dan Sebahagian Buta (aktifkan jika anda tidak sepenuhnya buta).\n");

        // Malayalam
        translationsMap.put("ml", "•   ദിവസവും ഉദ്യോഗങ്ങളിലെ നിങ്ങളെ സഹായിക്കുന്നതിനായി പ്രവേശിപ്പിക്കാവുന്ന മൂന്ന് ചാനലുകളുണ്ട്: വായിക്കുക, വസ്തു, മറ്റ് എന്നിവ, താങ്കളുടെ കൂടെ താങ്കളുടെ കാര്യങ്ങളിലേക്ക് സഹായകമായി. താങ്കളുടെ ചെയര്‍സില്‍ അടങ്ങിയിട്ടുള്ള ബട്ടണുകള്‍ മാത്രമാണ് ചാനലുകളെ പ്രതിനിധിക്കുന്നത്.\nഅപ്ലിക്കേഷനുടല്‍നിന്റെ മുഖം വടക്ക് പുറത്തുള്ള ഒരു മൈക്രോഫോണ്‍ ബട്ടണ്‍ ഉണ്ട്, അതില്‍ ഒരു വചനം ചൊല്ലി നിങ്ങള്‍ ആവശ്യപ്പെടുന്ന ഏതൊരു ചാനലിലേക്ക് നീങ്ങാം. ഉദാഹരണത്തിന് 'വായിക്കുക' എന്ന് പറഞ്ഞാല്‍ അത് നിങ്ങളെ അവിടെയേക്കു കൊണ്ടുവായിക്കും.\n•   മേലിന്നെയുള്ള നാവിഗേഷന്‍ ബാരില്‍ വലതുവശത്ത് സെറ്റിംഗ്സ് ബട്ടണ്‍ ഉണ്ട്; അതിനെ അമര്‍ത്തിയാല്‍ ഞങ്ങളുടെ അപ്ലിക്കേഷന്‍ പ്രമാണം ക്സമ്മം നിയന്ത്രിക്കുന്ന ഓപ്‌ഷനുകളും ലഭിക്കും: ഡിഫോള്‍ട്ട് ഭാഷ, സ്പീച് റേറ്റ് (എങ്ങനെ വേഗത്തില്‍ അപ്ലിക്കേഷന്‍ സംസാരിക്കുന്നതെന്ന്), പാര്‍ട്ടിയല്‍ ബ്ലൈന്‍ഡ് (നിങ്ങള്‍ പൂര്‍ണ്ണമായും കുട്ടിക്കാരന്‍ അല്ലെങ്കില്‍ കുട്ടിക്കാരന്‍റെ പക്ഷം കുട്ടിക്കാരന്‍) (നിങ്ങള്‍ അവിടെയില്‍ പൂര്‍ണ്ണമായി അന്ധനായിരുന്നാല്‍ അതിനെ സക്രിയമാക്കുക).\n");

// Marathi
        translationsMap.put("mr", "•   मुख्य स्क्रीनवर तीन चॅनेल उपलब्ध आहेत आपल्या दैनंदिन क्रियाकलापांमध्ये आपल्याला सहाय्य करण्यासाठी: वाचा, ऑब्जेक्ट, आणि ट्रांसलेट, ज्यांना खालील बटणांनी प्रतिनिधित्त्व केले आहे.\nएक मायक्रोफोन बटण मोबाईल अ‍ॅपच्या मुख्य स्क्रीनवर असते, आणि तुम्ही त्याचा वापर कोणत्याही चॅनेलवर खोलण्यासाठी वापरू शकता. उदाहरणार्थ, म्हणा 'वाचा' आणि ते तुम्हाला त्यांना घेऊ जाईल.\n•   वरच्या नेव्हिगेशन बारच्या उजव्या कोनात एक सेटिंग्जबटण आहे, आणि त्यावर क्लिक करून आपल्याला आमच्या अ‍ॅपचे सानुकूलीकरण करण्याची परवानगी मिळेल: मुख्य भाषा, भाषण गति (तुम्हाला किती वेगवेगळ्या गोष्टी आपल्या अ‍ॅपला बोलवायची आहे ते), आणि अर्धदृष्टी (त्याचा सक्रिय करा जर तुम्हाला पूर्ण बोट नाही आहे).\n");

        // Norwegian
        translationsMap.put("no", "•   Hovedskjermen har tre kanaler tilgjengelig for å hjelpe deg med hverdagslige aktiviteter: les, objekt, og oversett, som er representert av knappene nedenfor.\nEn mikrofonknapp er plassert midt på appens hovedskjerm, og du kan bruke den til å åpne hvilken som helst kanal du vil. For eksempel, si 'les', og det vil ta deg dit.\n•   Det er en innstillingsknapp på høyre side av toppnavigasjonsfeltet, og ved å klikke på den vil du få muligheter til å tilpasse vår app: Standard språk, Talehastighet (hvor fort du vil at appen skal snakke), og Delvis blind (aktiver den hvis du ikke er helt blind).\n");

        // Polish
        translationsMap.put("pl", "•   Główny ekran posiada trzy dostępne kanały, które pomagają w codziennych czynnościach: czytaj, obiekt i tłumacz, które są reprezentowane przez przyciski poniżej.\nJedna przycisk mikrofonu znajduje się na środku głównego ekranu aplikacji, i możesz go użyć, aby otworzyć dowolny kanał, który chcesz. Na przykład, powiedz 'czytaj', a przeniesie cię tam.\n•   Na prawym skraju górnej belki nawigacyjnej znajduje się przycisk ustawień, po kliknięciu którego uzyskasz opcje dostosowania naszej aplikacji: Domyślny język, Szybkość mowy (jak szybko chcesz, żeby aplikacja mówiła) oraz Częściowo niewidomy (włącz to, jeśli nie jesteś całkowicie niewidomy).\n");

// Portuguese
        translationsMap.put("pt", "•   A tela principal possui três canais acessíveis para ajudá-lo em suas atividades diárias: ler, objeto e traduzir, representados pelos botões abaixo.\nUm botão de microfone está localizado no meio da tela principal do aplicativo e você pode usá-lo para abrir qualquer canal que desejar. Por exemplo, diga 'ler' e ele o levará até lá.\n•   Há um botão de configuração no lado direito da barra de navegação superior e ao clicar nele você terá opções para personalizar nosso aplicativo: Idioma padrão, Velocidade da fala (o quão rápido você quer que o aplicativo fale) e Parcialmente Cego (ative-o se você não for completamente cego).\n");

        // Romanian
        translationsMap.put("ro", "•   Ecranul principal are trei canale accesibile pentru a vă ajuta în activitățile de zi cu zi: citire, obiect și traducere, care sunt reprezentate de butoanele de mai jos.\nUn buton de microfon este situat în mijlocul ecranului principal al aplicației și îl puteți folosi pentru a deschide orice canal doriți. De exemplu, spuneți 'citire' și vă va duce acolo.\n•   Există un buton de setare în partea dreaptă a barei de navigare superioare și făcând clic pe el veți avea opțiuni de personalizare a aplicației noastre: Limba implicită, Viteza vorbirii (cât de repede doriți ca aplicația să vorbească) și Parțial Orb (activați-l dacă nu sunteți complet orb).\n");

        // Russian
        translationsMap.put("ru", "•   На главном экране три доступных канала, которые помогают вам в повседневных делах: чтение, объект и перевод, которые представлены кнопками ниже.\nОдна кнопка микрофона расположена посередине основного экрана приложения, и вы можете использовать ее, чтобы открыть любой канал, который вам нужен. Например, скажите 'чтение', и оно перенесет вас туда.\n•   Справа от верхней панели навигации есть кнопка настроек, нажав на которую, вы получите возможность настроить наше приложение: Язык по умолчанию, Скорость речи (насколько быстро вы хотите, чтобы приложение говорило) и Частично слепой (включите его, если вы не полностью слепы).\n");

// Slovak
        translationsMap.put("sk", "•   Hlavná obrazovka má tri kanály, ktoré vám pomáhajú pri každodenných aktivitách: čítanie, objekt a preklad, ktoré sú reprezentované tlačidlami nižšie.\nJedno tlačidlo mikrofónu je umiestnené v strede hlavnej obrazovky aplikácie a môžete ho použiť na otvorenie akéhokoľvek kanála, ktorý chcete. Napríklad povedzte 'čítanie' a prevezme vás tam.\n•   Vpravo od horného navigačného panela je tlačidlo nastavení a po jeho stlačení získate možnosti prispôsobenia našej aplikácie: Predvolený jazyk, Rýchlosť reči (ako rýchlo chcete, aby aplikácia hovorila) a Čiastočne slepý (aktivujte ho, ak nie ste úplne slepí).\n");

        // Spanish
        translationsMap.put("es", "•   La pantalla principal tiene tres canales accesibles para ayudarte en tus actividades diarias: leer, objeto y traducir, que están representados por los botones debajo.\nUn botón de micrófono se encuentra en el medio de la pantalla principal de la aplicación y puedes usarlo para abrir cualquier canal que desees. Por ejemplo, di 'leer' y te llevará allí.\n•   Hay un botón de configuración en el lado derecho de la barra de navegación superior y al hacer clic en él, tendrás opciones para personalizar nuestra aplicación: Idioma predeterminado, Velocidad del habla (qué tan rápido quieres que hable la aplicación) y Parcialmente ciego (actívalo si no estás completamente ciego).\n");

        // Swedish
        translationsMap.put("sv", "•   Huvudskärmen har tre kanaler tillgängliga för att hjälpa dig med dina vardagliga aktiviteter: läsa, objekt och översätt, som representeras av knapparna nedanför.\nEn mikrofonknapp är placerad i mitten av appens huvudskärm, och du kan använda den för att öppna vilken kanal du vill. Till exempel, säg 'läsa' och det tar dig dit.\n•   Det finns en inställningsknapp till höger om den övre navigeringsfältet, och genom att klicka på den får du alternativ att anpassa vår app: Standardspråk, Talhastighet (hur snabbt du vill att appen ska prata) och Delvis blind (aktivera det om du inte är helt blind).\n");

// Tamil
        translationsMap.put("ta", "•   தலைப்பு திரையில் உங்கள் தினசரி செயல்களை உதவுவதற்கான மூன்று சேனல்கள் உள்ளன: படித்தல், பொருள், மொழிபெயர்ப்பு, அது கீழே உள்ள பொத்தான்கள் மூலம் பிரதிநிதித்துவம் செய்யப்படுகின்றன.\nஒரு மைக்ரோஃபோன் பொத்தான் பயன்படுத்தப்பட்ட சென்னல் போல பயன்படுத்தலாம். சில உதாரணங்களாக, 'படித்தல்' என்று சொல்லுங்கள் மற்றும் அது உங்களை அங்குக்கு கொண்டு வரும்.\n•   மேல் பட்டி வழியில் வலது புறத்தில் அமைப்பு பொத்தான் ஒரு அமைப்பு பொத்தான் உள்ளது மற்றும் அதைக் கிளிக் செய்வதன் மூலம் எங்கள் பயன்பாட்டை உருவாக்க விரும்புகின்ற விருப்பங்கள் உங்களுக்கு கிடைக்கும்: இயல்புநிலை மொழி, பேச்சு வேகம் (உங்கள் பயன்பாட்டிற்கு எப்படி வேகமாக பேசுவது என்பதனை நீங்கள் விரும்புகின்றீர்கள்) மற்றும் பகுப்பாய்வு பாராளுமன்றம் (நீங்கள் முழுவதும் குருட்டானால் அதை செயலாக்குங்கள்).\n");

        // Telugu
        translationsMap.put("te", "•   ముఖ్య తేదీవిన కార్యాచరణలకు సహాయపడటానికి మూడు చానెల్లు అందుబాటులో ఉన్నాయి: చదువు, ఆబ్జెక్ట్, మరియు అనువాదం, అవి కొనసాగే బటన్‌లతో సూచించబడ్డాయి.\nయాజమాన్య ముయ్యల బటన్ యందు అమ్మిన ఒక మైక్రోఫోన్ బటన్ ముఖ్య తేదీవిన యాప్ ముఖ్య తేదీవిని తెరువుతుంది, మీరు ఏమి అనుకుంటే అది ఓపెన్ చేయవచ్చు. ఉదాహరణకు, 'చదువు' అని చెప్పండి మరియు అట్లు అతనికి తీసుకోవడం.\n•   పైన సరిహద్దు నావిగేషన్ బార్ యొక్క కుడివై సెట్టింగ్స్ బటన్ ఒక సెట్టింగ్స్ బటన్ ఉంది మరియు దానిపై క్లిక్ చేస్తే మేము మా అనువర్తనాన్ని విన్యసించడానికి ఎంతో ఎంతో ఎంతో ఐచ్చికలు ఇస్తాం: డిఫాల్ట్ భాష (మీరు అప్లికేషన్ స్పీక్ చేయడానికి ఎటువంటి వేగం కావాలి) మరియు పార్టియల్లీ బ్లైండ్ (మీరు పూర్తిగా అనుబంధించలేకపోయినా అది సక్రియం చేయండి).\n");

        // Thai
        translationsMap.put("th", "•   หน้าจอหลักมีช่องสามรูปแบบที่สามารถใช้ในการช่วยคุณในกิจกรรมประจำวัน: อ่าน, วัตถุ, และแปลภาษาซึ่งมีการแสดงผลด้วยปุ่มด้านล่าง\nปุ่มไมโครโฟนหนึ่งอยู่ตรงกลางของหน้าจอหลักของแอปพลิเคชันและคุณสามารถใช้งานได้เพื่อเปิดช่องใดช่องหนึ่งที่คุณต้องการ ตัวอย่างเช่น พูด 'อ่าน' และมันจะพาคุณไปที่นั่น\n•   มีปุ่มการตั้งค่าทางด้านขวาของแถบนำทางบน โดยคลิกที่จะให้คุณเลือกแก้ไขแอปของเรา: ภาษาเริ่มต้น, อัตราการพูด (ความเร็วที่คุณต้องการให้แอปพูด) และตั้งค่าส่วนบางส่วนบนตัว (เปิดใช้งานหากคุณไม่ตาบอดเสมือน)\n");

// Turkish
        translationsMap.put("tr", "•   Ana ekran, günlük aktivitelerinizde size yardımcı olmak için erişilebilir üç kanala sahiptir: okuma, nesne ve çeviri, bunlar aşağıdaki düğmelerle temsil edilir.\nBir mikrofon düğmesi, uygulamanın ana ekranının ortasında bulunur ve istediğiniz herhangi bir kanalı açmak için kullanabilirsiniz. Örneğin, 'okuma' deyin ve sizi oraya götürecektir.\n•   Bir mikrofon düğmesi, uygulamanın ana ekranının ortasında bulunur ve istediğiniz herhangi bir kanalı açmak için kullanabilirsiniz. Örneğin, 'okuma' deyin ve sizi oraya götürecektir.\n•   Üst gezinme çubuğunun sağ tarafında bir ayar düğmesi bulunur ve tıklayarak uygulamamızı özelleştirmek için seçenekler sunar: Varsayılan Dil, Konuşma Hızı (uygulamanın ne kadar hızlı konuşmasını istediğinizi belirler) ve Kısmen Kör (tamamen kör değilseniz etkinleştirin).");

        // Ukrainian
        translationsMap.put("uk", "•   Основний екран має три доступні канали для допомоги в повсякденних справах: читання, об'єкт і переклад, які представлені кнопками нижче.\nОдин кнопка мікрофона знаходиться в середині головного екрана програми, і ви можете використовувати її для відкриття будь-якого каналу, який вам подобається. Наприклад, скажіть 'читання', і вона вас туди поведе.\n•   Один кнопка мікрофона знаходиться в середині головного екрана програми, і ви можете використовувати її для відкриття будь-якого каналу, який вам подобається. Наприклад, скажіть 'читання', і вона вас туди поведе.\n•   З правого боку верхньої панелі навігації є кнопка налаштувань, яка, натиснута, дає вам можливість настроїти наш додаток: Мова за замовчуванням, Швидкість мовлення (наскільки швидко ви хочете, щоб програма говорила) та Частково Сліпий (активуйте це, якщо ви не повністю сліпі).");

        // Urdu
        translationsMap.put("ur", "•   مرکزی اسکرین میں روزمرہ کی انشائیات میں آپ کی مدد کے لئے تین چینلز دستیاب ہیں: پڑھنا، اشیاء، اور ترجمہ، جو نیچے دیئے گئے بٹنوں کی صورت میں ظاہر ہیں۔\nایک مائیکروفون بٹن ایپ کی مرکزی اسکرین کے درمیان میں ہوتا ہے، اور آپ اسے کسی بھی چینل کو کھولنے کے لئے استعمال کر سکتے ہیں۔ مثال کے طور پر، 'پڑھنا' کہیں اور یہ آپ کو وہاں لے جائے گا۔\n•   ایک مائیکروفون بٹن ایپ کی مرکزی اسکرین کے درمیان میں ہوتا ہے، اور آپ اسے کسی بھی چینل کو کھولنے کے لئے استعمال کر سکتے ہیں۔ مثال کے طور پر، 'پڑھنا' کہیں اور یہ آپ کو وہاں لے جائے گا۔\n•   اوپری نیویگیشن بار کے دائیں طرف ایک سیٹنگز بٹن ہوتا ہے، جس پر کلک کرنے سے آپ کے پاس ہماری ایپ کو کسٹمائز کرنے کے اختیارات دستیاب ہوتے ہیں: ڈیفالٹ زبان، گفتگو کی شرح (آپ کو کتنی تیزی سے ایپ بولنا چاہتے ہیں) اور جزوی طور پر اندھا (اگر آپ مکمل طور پر اندھے نہیں ہیں تو اسے فعال کریں)۔");

// Vietnamese
        translationsMap.put("vi", "•   Màn hình chính có ba kênh có sẵn để hỗ trợ bạn trong các hoạt động hàng ngày: đọc, đối tượng và dịch, được đại diện bằng các nút ở dưới.\nNút microphone được đặt ở giữa màn hình chính của ứng dụng, và bạn có thể sử dụng nó để mở bất kỳ kênh nào bạn muốn. Ví dụ, nói 'đọc' và nó sẽ đưa bạn đến đó.\n•   Một nút microphone được đặt ở giữa màn hình chính của ứng dụng, và bạn có thể sử dụng nó để mở bất kỳ kênh nào bạn muốn. Ví dụ, nói 'đọc' và nó sẽ đưa bạn đến đó.\n•   Có một nút cài đặt ở phía bên phải của thanh điều hướng trên cùng và bấm vào đó sẽ cho bạn các tùy chọn để tùy chỉnh ứng dụng của chúng tôi: Ngôn ngữ Mặc định, Tốc độ Nói (bạn muốn ứng dụng nói nhanh như thế nào), và Một phần Mù (bật nó nếu bạn không mù hoàn toàn).");

        // Tagalog
        translationsMap.put("tl", "•   Ang pangunahing screen ay may tatlong mga channel na magagamit upang tulungan ka sa iyong mga araw-araw na gawain: magbasa, bagay, at isalin, na kinakatawan ng mga button sa ibaba.\nMay isang microphone button na matatagpuan sa gitna ng pangunahing screen ng app, at maaari mong gamitin ito upang buksan ang anumang channel na gusto mo. Halimbawa, sabihin ang 'magbasa' at dadalhin ka doon.\n•   May isang microphone button na matatagpuan sa gitna ng pangunahing screen ng app, at maaari mong gamitin ito upang buksan ang anumang channel na gusto mo. Halimbawa, sabihin ang 'magbasa' at dadalhin ka doon.\n•   Mayroong isang setting button sa kanang bahagi ng top navigation bar at pag-click dito ay magbibigay sa iyo ng mga opsyon upang i-customize ang aming app: Default Language, Speech Rate (kung gaano kabilis mo gustong magsalita ang app), at Partially Blind (paganahin ito kung hindi ka lubos na bulag).");

        // Swahili
        translationsMap.put("sw", "•   Skrini kuu ina vichaneli vitatu vinavyopatikana kusaidia katika shughuli zako za kila siku: soma, kitu, na tafsiri, ambavyo vinawakilishwa na vitufe chini.\nKitufe cha micropone kipo katikati ya skrini kuu ya programu, na unaweza kutumia kufungua chaneli yoyote unayopenda. Kwa mfano, sema 'soma' na itakuchukua hapo.\n•   Kitufe cha micropone kipo katikati ya skrini kuu ya programu, na unaweza kutumia kufungua chaneli yoyote unayopenda. Kwa mfano, sema 'soma' na itakuchukua hapo.\n•   Kuna kitufe cha mipangilio upande wa kulia wa upau wa urambazaji wa juu na kubonyeza kitakupa chaguzi za kubinafsisha programu yetu: Lugha ya Default, Kasi ya Hotuba (jinsi haraka unataka programu izungumze), na Kipofu kwa Sehemu (uiwezeshe kama hauko kipofu kabisa).");

// Slovenian
        translationsMap.put("sl", "•   Glavni zaslon ima tri dostopne kanale, ki vam pomagajo pri vaših vsakodnevnih dejavnostih: branje, predmet in prevod, ki so predstavljeni z gumbi spodaj.\nEn gumb za mikrofon je nameščen v sredini glavnega zaslona aplikacije in ga lahko uporabite za odpiranje katerega koli kanala želite. Na primer, recite 'branje' in odprlo vas bo tja.\n•   En gumb za mikrofon je nameščen v sredini glavnega zaslona aplikacije in ga lahko uporabite za odpiranje katerega koli kanala želite. Na primer, recite 'branje' in odprlo vas bo tja.\n•   Na desni strani zgornje navigacijske vrstice je gumb za nastavitve in ko nanj kliknete, vam ponudi možnosti prilagajanja naše aplikacije: privzeti jezik, hitrost govora (kako hitro želite, da aplikacija govori) in delno slep (omogočite, če niste popolnoma slepi).");

        // Maltese
        translationsMap.put("mt", "•   Is-skrin prinċipali għandu tliet kanali accessibbli biex jgħinuk fil-attivitajiet tiegħek ta' kuljum: qara, oġġett, u traduċi, li huma rappreżentati mill-buttuni taħt.\nButtur tal-mikrofon wieħed huwa msemmen fil-meżżu tas-skrin prinċipali tal-app, u tista' tużah biex tiftaħ xi kanal li tixtieq. Per eżempju, qal 'qara' u se jieħu l-ebda fejn tixtieq.\n•   Buttur tal-mikrofon wieħed huwa msemmen fil-meżżu tas-skrin prinċipali tal-app, u tista' tużah biex tiftaħ xi kanal li tixtieq. Per eżempju, qal 'qara' u se jieħu l-ebda fejn tixtieq.\n•   Hemm buttuna ta' settings fuq il-ġewwa tal-barrani u li jklikkja fuqu ser jipprovdi l-ebda ħtiġijiet biex tippreżenta l-app tagħna: Lingwa Default, Raġġ tal-Konverżazzjoni (kif b'żgħożi inti tixtieq li l-app titkellem), u jippermettuh Mixwi (eżibixxiha jekk inti mhux kompletament mixwi).");

        // Macedonian
        translationsMap.put("mk", "•   Главниот екран има три достапни канали за да ви помогне во вашите секојдневни активности: читање, објект и преведување, кои се претставени со копчиња подолу.\nЕдно копче за микрофон е лоцирано во средина на главниот екран на апликацијата и може да го користите за да отворите било кој канал што сакате. На пример, речете 'читање' и ќе ве одведе таму.\n•   Едно копче за микрофон е лоцирано во средина на главниот екран на апликацијата и може да го користите за да отворите било кој канал што сакате. На пример, речете 'читање' и ќе ве одведе таму.\n•   На десната страна на горниот крај на навигациската лента има копче за поставувања и кога ќе кликнете на него, ќе ви даде опции за прилагодување на нашата апликација: јазик по подразбирање, брзина на говор (колку брзо сакате апликацијата да зборува) и делумно слеп (овозможете го ако не сте целосно слепи).");

// Hebrew
        translationsMap.put("he", "•   המסך הראשי כולל שלושה ערוצים נגישים לסיוע בפעילויות היומיומיות שלך: קריאה, עצם, ותרגום, שמיוצגים על ידי הכפתורים למטה.\nכפתור מיקרופון אחד ממוקם באמצע המסך הראשי של האפליקציה, ואתה יכול להשתמש בו כדי לפתוח כל ערוץ שתרצה. לדוגמה, אמור 'קריאה' והוא יביא אותך לשם.\n•   כפתור מיקרופון אחד ממוקם באמצע המסך הראשי של האפליקציה, ואתה יכול להשתמש בו כדי לפתוח כל ערוץ שתרצה. לדוגמה, אמור 'קריאה' והוא יביא אותך לשם.\n•   קיים כפתור הגדרות בצד ימין של סרגל הניווט העליון ולחיצה עליו תעניק לך אפשרויות להתאמת האפליקציה שלנו: שפת ברירת המחדל, מהירות הדיבור (כמה מהר אתה רוצה את האפליקציה לדבר), וחלקית עיוור (הפעל אותו אם אינך עיוור לחלוטין).");

        // Haitian
        translationsMap.put("ht", "•   Ekran prensipal la gen twa chanèl ki aksesib pou asiste ou nan aktivite chak jou ou: li, objè, ak tradui, ki reprezante pa bouton yo anba.\nYon bouton mikwòfòn ki genyen nan mitan ekran prensipal aplikasyon an, epi ou ka itilize li pou ou louvri nenpòt chanèl ou vle. Pa egzanp, di 'li' e li pral mennen ou la.\n•   Yon bouton mikwòfòn ki genyen nan mitan ekran prensipal aplikasyon an, epi ou ka itilize li pou ou louvri nenpòt chanèl ou vle. Pa egzanp, di 'li' e li pral mennen ou la.\n•   Gen yon bouton anviwònman sou bò dwat nan bara navigasyon an atòch epi klike sou li pral bay ou opsyon pou pesonalize aplikasyon nou yo: Lang Default, Vitès Pale (kijan vit ou vle aplikasyon an pale), ak Pasyèlman Aveg (pèmèt li si ou pa aveg tout bon vre).");

        // Georgian
        translationsMap.put("ka", "•   საძიებო ეკრანი შეიცავს სამი გარემო, რომელიც თქვენს ყოველდღიურ აქტივობებში გეხმარებათ: კითხვა, ობიექტი და თარგმანი, რომელიც აღწერილია ღილაკებით ქვეითი.\nერთი მიკროფონის ღილაკი მდიდარე ეკრანზე გადააქვეყნებულია აპლიკაციის ძირითად გვერდზე და თქვენ შეგიძლიათ გამოიხსნათ ნებისმიერი ჩანაწერი, რომელიც გსურთ. მაგალითად, თქვენ შეუკითხავთ 'კითხვა' და ის გადადის იქ.\n•   ერთი მიკროფონის ღილაკი მდიდარე ეკრანზე გადააქვეყნებულია აპლიკაციის ძირითად გვერდზე და თქვენ შეგიძლიათ გამოიხსნათ ნებისმიერი ჩანაწერი, რომელიც გსურთ. მაგალითად, თქვენ შეუკითხავთ 'კითხვა' და ის გადადის იქ.\n•   ზემო მარჯვნივ ნავიგაციის ზოლზე გვერდის არის პარამეტრების ღილაკი და დაჭერით მას თქვენ შეგიძლიათ მოისარგებლოთ ჩვენი აპლიკაციის პარამეტრები: ნაგულისხმევი ენა, ლექსიკონის სიჩქარე (რამდე სწრაფად გსურთ აპლიკაცია გელოდოთ) და ნაწილობრივი ბრუნვა (ჩართეთ თუ თქვენ არ ხართ სრულიად ბრუნი).");

// Croatian
        translationsMap.put("hr", "•   Glavni zaslon ima tri pristupačna kanala koji vam pomažu u svakodnevnim aktivnostima: čitanje, objekt i prevođenje, koji su prikazani gumbima ispod.\nJedan gumb za mikrofon nalazi se u sredini glavnog zaslona aplikacije i možete ga koristiti za otvaranje bilo kojeg kanala koji želite. Na primjer, recite 'čitanje' i odvest će vas tamo.\n•   Jedan gumb za mikrofon nalazi se u sredini glavnog zaslona aplikacije i možete ga koristiti za otvaranje bilo kojeg kanala koji želite. Na primjer, recite 'čitanje' i odvest će vas tamo.\n•   Na desnoj strani gornje navigacijske trake nalazi se gumb postavki i klikom na njega dobit ćete opcije za prilagodbu naše aplikacije: zadani jezik, brzina govora (koliko brzo želite da aplikacija govori) i djelomično slijepi (omogućite ga ako niste potpuno slijepi).");

        // Catalan
        translationsMap.put("ca", "•   La pantalla principal té tres canals accessibles per ajudar-te en les teves activitats diàries: llegir, objecte i traduir, que es representen amb els botons a continuació.\nUn botó de micròfon es troba al mig de la pantalla principal de l'aplicació i el pots utilitzar per obrir qualsevol canal que vulguis. Per exemple, digues 'llegir' i et portarà allà.\n•   Un botó de micròfon es troba al mig de la pantalla principal de l'aplicació i el pots utilitzar per obrir qualsevol canal que vulguis. Per exemple, digues 'llegir' i et portarà allà.\n•   Hi ha un botó de configuració al costat dret de la barra de navegació superior i clicant-hi obtindràs opcions per personalitzar la nostra aplicació: Idioma predeterminat, Velocitat del parlant (quanta rapidesa vols que parli l'aplicació) i Parcialment cec (activa'l si no ets completament cec).");

        // Albanian
        translationsMap.put("sq", "•   Ekrani kryesor ka tre kanale të qasshëm për t'ju ndihmuar në aktivitetet tuaja të përditshme: lexim, objekt, dhe përkthim, të cilat janë përfaqësuar me butonat më poshtë.\nNjë buton mikrofoni ndodhet në mes të ekranit kryesor të aplikacionit dhe mund ta përdorni për të hapur cilindo kanal që dëshironi. Për shembull, thoni 'lexim' dhe ju do të çon atje.\n•   Një buton mikrofoni ndodhet në mes të ekranit kryesor të aplikacionit dhe mund ta përdorni për të hapur cilindo kanal që dëshironi. Për shembull, thoni 'lexim' dhe ju do të çon atje.\n•   Ka një buton konfigurimi në anën e djathtë të shiritit të navigimit të sipërm dhe duke klikuar aty do të merrni opsione për të personalizuar aplikacionin tonë: Gjuha e Paracaktuar, Shpejtësia e Bisedimit (sa shpejt dëshironi që aplikacioni të flasë), dhe Parsialisht i Verbër (e aktivizoni nëse nuk jeni krejtësisht i verbër).");

    }
}
